### ISSUE TITLE
App crash in android 12 

### ISSUE THREAD

**Issue by pranavo72bex** [thanhnamitit/programmable_video#1]
https://gitlab.com/twilio-flutter/programmable-video/-/issues/198

```twilio_programmable_video_platform_interface:
    git:
      url: git@github.com:thanhnamitit/programmable_video.git
      ref: master
      path: programmable_video_platform_interface```
      
twilio_programmable_video:
    git:
      url: https://github.com/thanhnamitit/programmable_video/tree/fix_bug_crash
      ref: 59db893
      
I try both but it  fail to add in  project clone for testing purpose ... latest version of **twilio_programmable_video 0.12.1** is also crashing

I think the latest android 12 support new android manifest permission for bluetooth in package level

**Comment by thanhnamitit** [comment]
I couldn't import directly by git URL as well. You should clone it to your project and import it like this

```
  twilio_programmable_video:
    path: {path_to_cloned_folder}/programmable_video/programmable_video
```

**Comment by pranavo72bex** [comment]
Finally solve the issue but is it safe to use `this code` in production app ?
**thanks you**

**Comment by thanhnamitit** [comment]
> Finally solve the issue but is it safe to use `this code` in production app ? **thanks you**

Yes. Our app has been released to production

**Comment by pranavo72bex** [comment]
Do you have any idea when this fix going to merge in package itself??

**Comment by thanhnamitit** [comment]
No, because my solution is only a workaround

**Comment by pranavo72bex** [comment]
This bug happen only in emulator not in real device.I just checked it on real device which running android 12 . thanks bro

**Comment by pranavo72bex** [comment]
any update regarding this bug ?
